package enums;

public enum ProcessingEvent {
    DOCUMENT_LOADED,
    PROCESSING_STARTED,
    METADATA_ADDED,
    WATERMARK_APPLIED,
    FORMAT_CONVERTED,
    VALIDATION_COMPLETED,
    PROCESSING_COMPLETED,
    PROCESSING_FAILED
}